version: '3.8'

services:
  ros: &ros-base
    image: ${DOCKER_REGISTRY}/ros:${DOCKER_TAG:-latest}
    build:
      context: ../../services/ros
      dockerfile: ros.dockerfile
      args:
        - BUILD_TARGET=${BUILD_TARGET}
        - BUILD_CREATED=${BUILD_CREATED}
        - BUILD_VERSION=${BUILD_VERSION}
        - GIT_COMMIT=${GIT_COMMIT}
      target: ${BUILD_TARGET}
    container_name: ros
    networks:
      default:
        aliases:
          - ros
    restart: unless-stopped
    environment:
      - BUILD_TARGET=${BUILD_TARGET}
      - HOST=${HOST}
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 socket
    profiles:
      - prod

  ros-dev:
    <<: *ros-base
    volumes:
      - ../../services/ros:/workspace # Volume mount for live reloading in dev
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 socket
    environment:
      - DISPLAY=${DISPLAY}
    profiles:
      - dev
