version: '3'

tasks:
  build:
    desc: Build
    cmds:
      - cd ros2_ws && colcon build --symlink-install && source ~/.bashrc

  run-test-node:
    desc: Run test node
    cmds:
      - ros2 run my_robot_controller test_node

  run-draw-circle:
    desc: Run draw circle
    cmds:
      - ros2 run my_robot_controller draw_circle
