version: '3'

tasks:
  build:
    desc: Build
    cmds:
      - cd ros2_ws && colcon build --symlink-install && source ~/.bashrc

  run-test-node:
    desc: Run test node
    cmds:
      - ros2 run my_robot_controller test_node

  run-draw-circle:
    desc: Run draw circle
    cmds:
      - ros2 run my_robot_controller draw_circle

  run-pose-subscriber:
    desc: Run pose subscriber
    cmds:
      - ros2 run my_robot_controller pose_subscriber

  run-turtle-controller:
    desc: Run turtle controller
    cmds:
      - ros2 run my_robot_controller turtle_controller
